sudo: required
services:
  - docker
before_install:
  - docker build -t lawrenceobrero/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true lawrenceobrero/react-test npm test

after_success:
  - docker build -t lawrenceobrero/multi-docker-client ./client
  - docker build -t lawrenceobrero/multi-docker-nginx ./nginx
  - docker build -t lawrenceobrero/multi-docker-server ./server
  - docker build -t lawrenceobrero/multi-docker-worker ./worker
  # Log in to the docker CLI
  
  # Push images to docker hub
