sudo: required
services:
  - docker
before_install:
  - docker build -t lawrenceobrero/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true lawrenceobrero/react-test npm test

after_success:
  - docker build -t lawrenceobrero/multi-docker-client ./client
  - docker build -t lawrenceobrero/multi-docker-nginx ./nginx
  - docker build -t lawrenceobrero/multi-docker-server ./server
  - docker build -t lawrenceobrero/multi-docker-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push lawrenceobrero/multi-docker-client
  - docker push lawrenceobrero/multi-docker-nginx
  - docker push lawrenceobrero/multi-docker-server
  - docker push lawrenceobrero/multi-docker-worker
